# Generated by Django 3.1.5 on 2021-09-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drink', 'نوشیدنی'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='dinner', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
