# Generated by Django 3.1.5 on 2021-09-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
    ]
